export const books = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    publisher: "HarperCollins",
    year: 1960,
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.standard.co.uk%2Fculture%2Fbooks%2Fbest-books-of-2018-a3997146.html&psig=AOvVaw3qKsnlS6y1M1V3JuToxJgl&ust=1691397193008000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCKj0yNjPx4ADFQAAAAAdAAAAABAQ",
    shelves: "Read",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    publisher: "Penguin Books",
    year: 1949,
    image: "https://m.media-amazon.com/images/I/71kxa1-0mfL.jpg",
    price: 8.99,
    shelves: "Read",
  },
  {
    id: 3,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    publisher: "Little, Brown and Company",
    year: 1951,
    image: "https://m.media-amazon.com/images/I/71kxa1-0mfL.jpg",
    price: 10.99,
    shelves: "Currently Reading",
  },
  {
    id: 4,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    publisher: "Scribner",
    year: 1925,
    image: "https://m.media-amazon.com/images/I/71FTb9X6wsL.jpg",
    price: 7.99,
    shelves: "Currently Reading",
  },
  {
    id: 5,
    title: "Brave New World",
    author: "Aldous Huxley",
    publisher: "Harper Perennial Modern Classics",
    year: 1932,
    image:
      "https://pagdandi.org/wp-content/uploads/2021/04/Brave-New-World.jpg",
    price: 12.99,
    shelves: "Want To Read",
  },
  {
    id: 6,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    publisher: "Penguin Classics",
    year: 1813,
    image: "https://m.media-amazon.com/images/I/71Q1tPupKjL.jpg",
    price: 6.99,
    shelves: "Want To Read",
  },
];
